FROM debian:bookworm

# Install the build dependencies using APT. List adapted from: https://mpd.readthedocs.io/en/latest/user.html#compiling-from-source
RUN apt-get update
RUN apt-get install -y --no-install-recommends pipx ninja-build git g++ pkgconf \
libfmt-dev \
libpcre2-dev \
libmad0-dev libmpg123-dev libid3tag0-dev \
libflac-dev libvorbis-dev libopus-dev libogg-dev \
libadplug-dev libaudiofile-dev libsndfile1-dev libfaad-dev \
libfluidsynth-dev libgme-dev libmikmod-dev libmodplug-dev \
libmpcdec-dev libwavpack-dev libwildmidi-dev \
libsidplay2-dev libsidutils-dev libresid-builder-dev \
libavcodec-dev libavformat-dev \
libmp3lame-dev libtwolame-dev libshine-dev \
libsamplerate0-dev libsoxr-dev \
libbz2-dev libcdio-paranoia-dev libiso9660-dev libmms-dev \
libzzip-dev \
libcurl4-gnutls-dev libexpat1-dev \
nlohmann-json3-dev \
libasound2-dev libao-dev libjack-jackd2-dev libopenal-dev \
libpulse-dev libshout3-dev \
libsndio-dev \
libmpdclient-dev \
libnfs-dev \
libupnp-dev \
libavahi-client-dev \
libsqlite3-dev \
libsystemd-dev \
libgtest-dev \
libicu-dev \
libchromaprint-dev \
libgcrypt20-dev \
libsystemd-dev \
libpipewire-0.3-dev 

# Meson must be installed through pip as the repo version is too old for MPD in Debian Bookworm.
RUN pipx install meson
RUN pipx ensurepath

ENTRYPOINT /bin/bash
